/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotebooksIdRouteImport } from './routes/_authenticated/notebooks.$id'
import { Route as AuthenticatedNotebooksIdPathRouteImport } from './routes/_authenticated/notebooks.$id.path'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotebooksIdRoute =
  AuthenticatedNotebooksIdRouteImport.update({
    id: '/notebooks/$id',
    path: '/notebooks/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotebooksIdPathRoute =
  AuthenticatedNotebooksIdPathRouteImport.update({
    id: '/path',
    path: '/path',
    getParentRoute: () => AuthenticatedNotebooksIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notebooks/$id': typeof AuthenticatedNotebooksIdRouteWithChildren
  '/notebooks/$id/path': typeof AuthenticatedNotebooksIdPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notebooks/$id': typeof AuthenticatedNotebooksIdRouteWithChildren
  '/notebooks/$id/path': typeof AuthenticatedNotebooksIdPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notebooks/$id': typeof AuthenticatedNotebooksIdRouteWithChildren
  '/_authenticated/notebooks/$id/path': typeof AuthenticatedNotebooksIdPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/notebooks/$id'
    | '/notebooks/$id/path'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/notebooks/$id' | '/notebooks/$id/path'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/notebooks/$id'
    | '/_authenticated/notebooks/$id/path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notebooks/$id': {
      id: '/_authenticated/notebooks/$id'
      path: '/notebooks/$id'
      fullPath: '/notebooks/$id'
      preLoaderRoute: typeof AuthenticatedNotebooksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notebooks/$id/path': {
      id: '/_authenticated/notebooks/$id/path'
      path: '/path'
      fullPath: '/notebooks/$id/path'
      preLoaderRoute: typeof AuthenticatedNotebooksIdPathRouteImport
      parentRoute: typeof AuthenticatedNotebooksIdRoute
    }
  }
}

interface AuthenticatedNotebooksIdRouteChildren {
  AuthenticatedNotebooksIdPathRoute: typeof AuthenticatedNotebooksIdPathRoute
}

const AuthenticatedNotebooksIdRouteChildren: AuthenticatedNotebooksIdRouteChildren =
  {
    AuthenticatedNotebooksIdPathRoute: AuthenticatedNotebooksIdPathRoute,
  }

const AuthenticatedNotebooksIdRouteWithChildren =
  AuthenticatedNotebooksIdRoute._addFileChildren(
    AuthenticatedNotebooksIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotebooksIdRoute: typeof AuthenticatedNotebooksIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotebooksIdRoute: AuthenticatedNotebooksIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
